<?php
include(TALLYBUILDER__SCONTENT_DIR.'scontent-blog.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-button.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-carousel.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-contactForm.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-grid.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-image.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-testimonials.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-text.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-title.php');
include(TALLYBUILDER__SCONTENT_DIR.'scontent-vcard.php');